[package]
name = "aio-plugin-tenant-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aio-plugin-tenant-model = { path = "../model" }
az-dioxus-admin-shell = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "86475520ed70465457fec636ebb001b1c9dc0bd8" }
az-ui-components = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "86475520ed70465457fec636ebb001b1c9dc0bd8" }
dill = "0.15.0"
dioxus = { version = "=0.7.9", default-features = false, features = ["macro", "html", "signals"] }
gloo-net = { version = "0.6.0", features = ["http", "json"] }
serde = "1.0.228"
serde_json = "1.0.145"
web-sys = { version = "0.3.77", features = ["Location", "Window"] }

[lints]
workspace = true
