[package]
name = "aio-plugin-tenant-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aio-plugin-identity-server = { git = "https://github.com/zjarlin/aio-plugin-identity.git", rev = "d689b45e9a2070721d953747e361f6fb7035f61f" }
aio-plugin-tenant-model = { path = "../model" }
anyhow = "1.0.99"
axum = "0.8.6"
dill = "0.15.0"
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "runtime-tokio-rustls"] }
uuid = { version = "1.18.1", features = ["v4"] }

[lints]
workspace = true
